name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get GitHub Actions IP
      id: ip
      uses: haythem/public-ip@v1.2
      
    - name: "AWS_SG_ID"
      run: |
        aws ec2 authorize-security-group-ingress \
        --group-id ${{ secrets.PROD_AWS_SG_ID }} \
        --protocol tcp --port 22 \
        --cidr ${{ steps.ip.outputs.ipv4 }}/32
