name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
      
    - name: Get GitHub Actions IP
      id: ip
      uses: haythem/public-ip@v1.2
      
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress \
        --group-id ${{ secrets.PROD_AWS_SG_ID }} \
        --protocol tcp --port 22 \
        --cidr ${{ steps.ip.outputs.ipv4 }}/32
