name: Deploy

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: 43.202.80.70 # 인스턴스 IP
          username: ubuntu # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: 22 # 접속포트
          script: | # 실행할 스크립트
            ls -al
            cd myapp/server
            ls -al
            # git pull
            # pm2 kill
            # pm2 start index.js

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: www-be
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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" # required
        if: always()
