name: Deploy

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: 43.202.80.70 # 인스턴스 IP
          username: ubuntu # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: 22 # 접속포트
          script: | # 실행할 스크립트
            ls -al
            cd myapp/server
            ls -al
            # git pull
            # pm2 kill
            # pm2 start index.js

      - name: send slack message
        uses: 8398a7/action-slack@v3
        with:
          mention: '김한이'
          if_mention: failure
          status: ${{ job.status }}
          fields: workflow,job,commit,message,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
