name: Deploy

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: 43.202.80.70 # 인스턴스 IP
          username: ubuntu # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: 22 # 접속포트
          script: | # 실행할 스크립트
            ls -al
            cd myapp/server
            ls -al
            # git pull
            # pm2 kill
            # pm2 start index.js

      - name: Notify Slack on Success
        if: success() # 이 step은 job이 성공한 경우에만 실행된다.
        id: slack-success
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "채널 ID",
              "attachments": [
                {
                  "color": "#36a64f", # 성공시 연두색
                  "title": "${{ github.repository }}", # 제목은 깃헙 레포지토리
                  "title_link": "https://github.com/${{github.repository}}", # 제목 클릭시 레포지토리로 이동
                  "text": "GitHub Action 성공",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Tag",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
